"""create businesses and scrape_jobs tables

Revision ID: 25210263f367
Revises: 
Create Date: 2026-03-27 20:06:08.680496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25210263f367'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('full_address', sa.Text(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('is_permanently_closed', sa.Boolean(), nullable=False),
    sa.Column('working_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('place_link', sa.Text(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_businesses_city_state', 'businesses', ['city', 'state'], unique=False)
    op.create_index(op.f('ix_businesses_place_id'), 'businesses', ['place_id'], unique=True)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('search_query', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_query')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_jobs')
    op.drop_index(op.f('ix_businesses_place_id'), table_name='businesses')
    op.drop_index('idx_businesses_city_state', table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
